# To change this template, choose Tools | Templates
# and open the template in the editor.

saml.idp.issuer=nexus:saml:issuer
saml.idp.privateKeyPassword=vijay125
saml.idp.privateKey=/home/ubuntu/tomcat/SAML/cert/nexusb2bnetwork.p12

saml.sp.entityId=urn:auth0:superservice:Amcap
saml.sp.consumerService=https://superservice.auth0.com/login/callback?connection=Amcap
saml.sp.relayState=https://api.superservice.com/parameters?system=amcap

